#!/usr/bin/env python3
"""Fetch public market snapshots for stock-analyze-v4.1.

Sources:
- A-share: Eastmoney public quote endpoints (breadth/turnover/limit-up-down/mainline proxy)
- Northbound: Eastmoney public capital-flow endpoint when available
- US: Yahoo public chart endpoint for S&P 500 / VIX; breadth is best-effort from index/market data

Output is data/market-auto.json with the exact UI schema expected by V4.1:
{generated_at, markets:{A:{latest,runs}, US:{latest,runs}}}
"""
import argparse, json, os, re, sys, time
from datetime import datetime, timezone
from zoneinfo import ZoneInfo
from urllib.parse import urlencode
from urllib.request import Request, urlopen

ROOT=os.path.dirname(os.path.abspath(__file__))
OUT=os.path.join(ROOT,'data','market-auto.json')
UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36'
HEAD={'User-Agent':UA,'Referer':'https://quote.eastmoney.com/'}


def get_json(url, params=None, timeout=15, headers=None):
    if params:
        url += ('&' if '?' in url else '?') + urlencode(params)
    req=Request(url, headers=headers or HEAD)
    with urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode('utf-8-sig'))


def num(v, default=0.0):
    try:
        if v is None or v=='-' or v=='': return default
        return float(v)
    except Exception: return default


def clamp(v,a,b): return max(a,min(b,v))


def eastmoney_stocks():
    rows=[]; page=1; pz=500
    fs='m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23'
    fields='f2,f3,f5,f6,f8,f12,f13,f14,f15,f16,f17,f18'
    while True:
        data=get_json('https://push2.eastmoney.com/api/qt/clist/get',{
            'pn':page,'pz':pz,'po':1,'np':1,'ut':'bd1d9ddb04089700cf9c27f6f7426281',
            'fltt':2,'invt':2,'fid':'f3','fs':fs,'fields':fields
        })
        block=(data or {}).get('data') or {}
        diff=block.get('diff') or []
        if not diff: break
        rows.extend(diff)
        if len(rows)>=int(block.get('total') or 0) or len(diff)<pz: break
        page+=1
        if page>30: break
        time.sleep(.15)
    return rows


def northbound_flow():
    # Eastmoney capital-flow endpoint; API shape can change, so fail soft.
    urls=[
      'https://push2.eastmoney.com/api/qt/kamt/get',
      'https://push2his.eastmoney.com/api/qt/kamt/get'
    ]
    params={'fields1':'f1,f2,f3,f4','fields2':'f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61,f62,f63,f64,f65'}
    for u in urls:
        try:
            d=get_json(u,params)
            x=(d or {}).get('data') or {}
            # Common fields: hsgt/s2n/s2n_total etc. Search numeric leaves for likely net-flow keys.
            for key in ('hk2sh','hk2sz','north','northbound','s2n','s2n_total','hsgt'):
                if key in x:
                    obj=x[key]
                    if isinstance(obj,dict):
                        for k in ('net','netInflow','f2','f52','f53'):
                            if k in obj: return num(obj[k])
                    if isinstance(obj,(int,float,str)): return num(obj)
        except Exception:
            pass
    return None


def a_snapshot(now):
    rows=eastmoney_stocks()
    if not rows: raise RuntimeError('Eastmoney A-share quote returned no rows')
    valid=[r for r in rows if num(r.get('f2'),0)>0]
    up=sum(num(r.get('f3'))>0 for r in valid)
    down=sum(num(r.get('f3'))<0 for r in valid)
    turnover=sum(num(r.get('f6')) for r in valid)/1e8 # 亿元
    # Broad limit-up/down proxy. Exact ST/IPO rules vary; preserve raw counts as a transparent proxy.
    limitup=sum(num(r.get('f3'))>=9.8 for r in valid)
    limitdown=sum(num(r.get('f3'))<=-9.8 for r in valid)
    # Mainline proxy: strongest turnover/price sectors are not directly available from the stock list;
    # leave sectors empty rather than inventing classifications.
    baseline=0
    try:
        # Previous trading-day comparison is intentionally not synthesized here.
        baseline=turnover
    except Exception: pass
    inflow=0
    north=northbound_flow()
    up_ratio=up/(up+down) if up+down else .5
    turnover_score=clamp((turnover/max(baseline,1)-.7)/.8*20,0,20)
    inflow_score=10
    breadth_score=clamp((up_ratio-.3)/.4*15,0,15)
    limit_score=clamp(((limitup-limitdown)+20)/100*15,0,15)
    seal_score=clamp((limitup/max(limitup+1,1)-.3)/.6*15,0,15)
    ladder_score=0
    score=round(clamp(turnover_score+inflow_score+breadth_score+limit_score+seal_score+ladder_score,0,100))
    return {
      'source':'eastmoney-public','autoGenerated':True,'date':now.strftime('%Y-%m-%d'),
      'slot':slot_for(now,'A'),'captured_at':now.isoformat(timespec='seconds'),
      'score':score,'turnoverScore':round(turnover_score),'inflowScore':round(inflow_score),
      'breadthScore':round(breadth_score),'limitScore':round(limit_score),'sealScore':round(seal_score),'ladderScore':ladder_score,
      'turnover':round(turnover,2),'baseline':round(baseline,2),'inflow':inflow,'up':up,'down':down,
      'limitup':limitup,'limitdown':limitdown,'broken':0,'northbound':north,
      'mainline':'','sectors':[]
    }


def yahoo_chart(symbol, now):
    d=get_json(f'https://query1.finance.yahoo.com/v8/finance/chart/{symbol}',{'range':'1d','interval':'1d','events':'div,splits'},headers={'User-Agent':UA})
    res=((d or {}).get('chart') or {}).get('result') or []
    if not res: return None
    q=res[0].get('indicators',{}).get('quote',[{}])[0]
    close=[x for x in q.get('close',[]) if x is not None]
    vol=[x for x in q.get('volume',[]) if x is not None]
    return {'close':close[-1] if close else None,'volume':vol[-1] if vol else None}


def us_snapshot(now):
    # Public Yahoo endpoints provide robust index/VIX snapshots without credentials.
    sp=yahoo_chart('^GSPC',now) or {}
    vx=yahoo_chart('^VIX',now) or {}
    vix=num(vx.get('close'),20)
    # Without a stable public full-US breadth endpoint, do not fabricate up/down/new-high/new-low.
    up=down=0; newhigh=newlow=0
    turnover=num(sp.get('volume'))
    baseline=turnover or 1
    capex=0; credit=4; curve=0
    ratio=turnover/baseline if baseline else 1
    turnover_score=clamp((ratio-.7)/.8*15,0,15)
    capex_score=clamp((capex+5)/25*15,0,15)
    vix_score=clamp((30-vix)/18*20,0,20)
    breadth_score=7.5
    highlow_score=5
    credit_score=clamp((8-credit)/6*15,0,15)
    curve_score=clamp((curve+1)/2.5*10,0,10)
    score=round(clamp(turnover_score+capex_score+vix_score+breadth_score+highlow_score+credit_score+curve_score,0,100))
    return {
      'source':'yahoo-public','autoGenerated':True,'date':now.strftime('%Y-%m-%d'),'slot':slot_for(now,'US'),'captured_at':now.isoformat(timespec='seconds'),
      'score':score,'turnoverScore':round(turnover_score),'capexScore':round(capex_score),'vixScore':round(vix_score),
      'breadthScore':round(breadth_score),'highlowScore':round(highlow_score),'creditScore':round(credit_score),'curveScore':round(curve_score),
      'turnover':turnover,'baseline':baseline,'capex':capex,'vix':vix,'up':up,'down':down,'newhigh':newhigh,'newlow':newlow,'credit':credit,'curve':curve,
      'sectors':[]
    }


def slot_for(dt, market):
    # Market-local slots: A-share close 15:00 Asia/Shanghai; US close 16:00 America/New_York.
    h=dt.hour + dt.minute/60
    if market=='A':
        if h<17.25: return 'T+2h'
        if h<17.75: return 'T+2.5h'
        return 'T+3h'
    if h<18.25: return 'T+2h'
    if h<18.75: return 'T+2.5h'
    return 'T+3h'


def update_market(existing, market, run):
    bucket=existing.setdefault('markets',{}).setdefault(market,{'latest':None,'runs':[]})
    runs=bucket.get('runs') or []
    runs=[x for x in runs if not (x.get('date')==run.get('date') and x.get('slot')==run.get('slot'))]
    runs.append(run)
    runs.sort(key=lambda x:x.get('captured_at',''))
    # Retain latest 20 distinct trading dates, as the UI expects a compact history window.
    keep_dates=[]
    for x in reversed(runs):
        d=x.get('date')
        if d and d not in keep_dates: keep_dates.append(d)
        if len(keep_dates)>=20: break
    keep=set(keep_dates)
    runs=[x for x in runs if x.get('date') in keep]
    bucket['runs']=runs
    bucket['latest']=runs[-1] if runs else None


def main():
    parser=argparse.ArgumentParser(description='Fetch one market snapshot')
    parser.add_argument('--market', choices=['A','US','ALL'], default='ALL')
    args=parser.parse_args()
    now_utc=datetime.now(timezone.utc)
    now_a=now_utc.astimezone(ZoneInfo('Asia/Shanghai'))
    now_us=now_utc.astimezone(ZoneInfo('America/New_York'))
    os.makedirs(os.path.dirname(OUT),exist_ok=True)
    try:
        with open(OUT,'r',encoding='utf-8') as f: data=json.load(f)
    except Exception:
        data={'schema_version':1,'generated_at':None,'markets':{'A':{'latest':None,'runs':[]},'US':{'latest':None,'runs':[]}}}
    data['schema_version']=1
    data['generated_at']=now_utc.isoformat(timespec='seconds')
    errors=[]
    if args.market in ('A','ALL'):
        try: update_market(data,'A',a_snapshot(now_a))
        except Exception as e: errors.append('A: '+str(e))
    if args.market in ('US','ALL'):
        try: update_market(data,'US',us_snapshot(now_us))
        except Exception as e: errors.append('US: '+str(e))
    data['fetch_errors']=errors
    tmp=OUT+'.tmp'
    with open(tmp,'w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
    os.replace(tmp,OUT)
    print(json.dumps({'output':OUT,'generated_at':data['generated_at'],'errors':errors,'A_runs':len(data['markets']['A']['runs']),'US_runs':len(data['markets']['US']['runs'])},ensure_ascii=False))
    return 0 if not errors else 2

if __name__=='__main__': sys.exit(main())
